CREATE TABLE public.user_data (
                                  id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  email varchar NOT NULL,
                                  "uuid" uuid NOT NULL,
                                  template_uuid uuid NOT NULL,
                                  token varchar NOT NULL,
                                  create_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                  update_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                  CONSTRAINT user_data_pk PRIMARY KEY (id)
);
